import { Metadata } from "next"
export const metadata:Metadata = {
  title: {
    default: 'Hello World App',
    template: '%s | Hello World App',
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
 <body>
      <header>
        <h1>
          this is a head tag
        </h1>
      </header>
     {children}

      <footer>
        <h1>

          this is the footer
        </h1>
      </footer>
      </body>
    </html>
  )
}
